version: '2'
services:
    editor-app:
        image: editor
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://editor-postgresql:5432/editor
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    editor-postgresql:
        extends:
            file: postgresql.yml
            service: editor-postgresql
